---
- name: Run Challenger Database Migrations
  hosts: db
  become: true

  tasks:
    - name: Ensure Challenger migrations directory exists
      file:
        path: "{{ migrations_root }}/challenger"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "0755"

    - name: Upload Challenger migration files
      copy:
        src: "files/challenger_migrations/"
        dest: "{{ migrations_root }}/challenger/"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
      register: upload_result

    - name: Display upload summary
      debug:
        msg: "Uploaded {{ upload_result.changed | ternary('new', 'existing') }} Challenger migrations"

    - name: Check PostgreSQL health
      command: docker exec challenger_postgres pg_isready -U challenger_user -d challenger_db
      args:
        chdir: "{{ project_dir }}/postgres"
      register: pg_health
      retries: 5
      delay: 2
      until: pg_health.rc == 0
      changed_when: false

    - name: Run Challenger database migrations
      command: docker compose --profile migrate run --rm flyway
      args:
        chdir: "{{ project_dir }}/postgres"
      register: migration_result
      failed_when: false  # Don't fail the playbook, handle errors gracefully

    - name: Display Challenger migration output
      debug:
        var: migration_result.stdout_lines

    - name: Display Challenger migration errors (if any)
      debug:
        var: migration_result.stderr_lines
      when: migration_result.rc != 0

    - name: Fail if Challenger migrations failed
      fail:
        msg: |
          Challenger migrations failed with exit code {{ migration_result.rc }}.
          Review the output above for details.
          To rollback: docker compose --profile migrate run --rm flyway undo
      when: migration_result.rc != 0

    - name: Challenger migrations completed successfully
      debug:
        msg: "✓ Challenger database migrations completed successfully"
      when: migration_result.rc == 0
